# Generated by Django 4.2.3 on 2023-07-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements',
            table='Advertisements',
        ),
    ]
